#!/bin/sh

virt-install \
    --name $1 \
    --hvm \
    --vcpus 2 \
    --memory 2048 \
    --disk path=/var/lib/libvirt/images/$1.img,size=20 \
    --network network=default \
    --graphics=none \
    --location /var/lib/libvirt/images/rhel-10.0-x86_64-dvd.iso,kernel=images/pxeboot/vmlinuz,initrd=images/pxeboot/initrd.img \
    --extra-args console=ttyS0 \
    --extra-args="inst.ks=file:rhel.cfg noipv6 hostname=$1" \
    --initrd-inject=./rhel.cfg \
    --wait=-1 \
    --noautoconsole &
