#!/bin/sh

if [ -z "$1" -o ! -f "$1" ];then
    echo "budget FILE"
    exit 0
fi

awk '
BEGIN {
    FS="," 
} 

{
    if ($1 ~ /^#/) { next }

    if ($1 < 0) {
        total_expense+=$1
        total_expense_person[$2]+=$1
    } else {
        total_income+=$1
        total_income_person[$2]+=$1
    }
    total_person[$2]+=$1
    total+=$1
}

END { 
    printf "-------------------------\n", total
    printf "Total Income: %s\n", total_income
    printf "Total Expense: %s\n", total_expense
    printf "Total: %s\n", total
    printf "-------------------------\n", total

    for (person in total_person) { 
        printf "%s Income: %s\n", person, total_income_person[person]
        printf "%s Expense: %s\n", person, total_expense_person[person]
        printf "%s Total: %s\n", person, total_person[person]
        printf "-------------------------\n", total
    }
}' "$1"
