#!/usr/bin/env python3

import email
import os
import sys

with open(sys.argv[1], 'r') as fp:
    message = email.message_from_file(fp)

if message.is_multipart:
    count = 0
    for part in message.walk():
        if part.get_content_maintype() == 'multipart':
            continue
        data = part.get_payload(decode=True)
        with open(f'out_{count:03d}.txt', 'w') as fp:
            fp.write(data.decode('utf-8'))
