#!/usr/bin/env python3

# Example:
# 9/1/2024,"","DEBIT","Withdrawal  @ MCDONALD's ....","-11.87","","","5601.99"

import csv, sys, os, re
import datetime, calendar

FASTFOOD=(
    '7-ELEVEN',
    'ARCO',
    'BURGER KING',
    'CAFE',
    'CARLS JR',
    'CHIPOTLE',
    'DEL TACO',
    'EL POLLO LOCO',
    'HABIT',
    'MEXICAN',
    'IN N OUT',
    'JERSEY MIKES',
    'JIMBOYS',
    'KFC',
    'MARKET'
    'MCDONALD',
    'MIYAKO',
    'NATIONS GIANT',
    'NOODLES',
    'PANERA BREAD',
    'PANDA EXPRESS',
    'SUBWAY',
    'TACO',
    'TERYAKI',
    'TOGO',
    'WENDY',
)

total = 0.0
debits = []

with open(sys.argv[1]) as fp:
    reader = csv.DictReader(fp)
    for row in reader:
        debit = row.get('Debit')
        descr = row.get('Description')
        temp  = row.get('Date')
        date  = datetime.datetime.strptime(temp, '%m/%d/%Y')
        for pattern in FASTFOOD:
            if re.search(pattern, descr):
                if debit.strip():
                     amount = (float(debit) * -1)
                     total = total + amount
                     print("%s %8.2f %-30s" % (date, amount, descr))
                     debits.append(dict(amount=amount, decr=descr, date=date))

print("")
print('Total: %.2f' % total)

current_month = None
current_total = 0

for i, record in enumerate(sorted(debits, key=lambda i:  i['date'])):

    month = record['date'].month
    amount = record['amount']

    if i == 0:
        current_month = month
        current_total = amount
    if i == len(debits) - 1:
        print('Month total %-10s: %8.2f' % (calendar.month_name[current_month], current_total))
    if current_month != month:
        print('Month total %-10s: %8.2f' % (calendar.month_name[current_month], current_total))
        current_month = month
        current_total = amount
    else:
        current_total += amount
