#!/bin/sh

tempdir=$(mktemp -d /tmp/virt-$1-XXXXX)
iso=rhel-9.5-x86_64-dvd.iso 

cat > $tempdir/kickstart.cfg << EOF
lang en_US.UTF-8
keyboard us
network --bootproto=dhcp --hostname=web
rootpw password
timezone America/Los_Angeles
text
skipx
zerombr
clearpart --all --initlabel
part swap --asprimary --size=1024
part / --fstype=xfs --asprimary --size=1 --grow
bootloader --location=mbr
user --name=admin --password=password --groups=wheel
eula --agreed
reboot

%packages
@^minimal-environment
%end
EOF

virt-install \
--name web \
--hvm \
--vcpus 2 \
--memory 2048 \
--disk path=/var/lib/libvirt/images/web.img,size=200 \
--network network=default \
--graphics=none \
--location /var/lib/libvirt/images/$iso \
--extra-args console=ttyS0 \
--extra-args='inst.ks=file:kickstart.cfg' \
--initrd-inject=$tempdir/kickstart.cfg \
--wait=-1 \
--noautoconsole &
